version: '3.6'
services:

  mysql:
    image: mysql:8
    container_name: tduck-mysql
    restart: always
    environment:
      - MYSQL_ROOT_PASSWORD=tduck@mysql
      - MYSQL_DATABASE=tduck
      - MYSQL_ROOT_HOST=%
      - TZ=Asia/Shanghai
    ports:
      - "3306:3306"
    volumes:
      - mysql-volume:/var/lib/mysql
      - ./init-db:/docker-entrypoint-initdb.d
    command: --default-authentication-plugin=mysql_native_password --character-set-server=utf8mb4 --collation-server=utf8mb4_unicode_ci


  tduck-platform:
    image: "tduckcloud/tduck-platform"
    container_name: tduck-platform
    restart: always
    ports:
      - "8999:8999" # API端口
    volumes:
      - "upload-volume:/application/BOOT-INF/lib/upload"  # 持久化上传的文件
    environment:
      - "JAVA_OPTS=-Duser.language=zh -XX:+UseG1GC"
      - "TZ=Asia/Shanghai"
      - "spring.datasource.url=jdbc:mysql://mysql:3306/tduck?useSSL=false&useUnicode=true&characterEncoding=utf8&serverTimezone=UTC&tinyInt1isBit=false" #数据库连接地址
      - "spring.datasource.username=root"
      - "spring.datasource.password=tduck@mysql"
    links:
      - mysql:mysql
    depends_on:
      - mysql

volumes:
  mysql-volume:
  upload-volume:
